FROM quay.io/coreos/dex:v2.8.1
FROM golang:alpine

COPY --from=0 /usr/local/bin/dex /usr/local/bin/dex

ENV APP_PATH /go/src/github.com/codeamp/circuit

RUN apk -U add alpine-sdk git gcc docker openssh
RUN go get github.com/cespare/reflex
RUN go get -u github.com/jteeuwen/go-bindata/...

RUN mkdir -p $APP_PATH
WORKDIR $APP_PATH

COPY . $APP_PATH
RUN mkdir -p assets/
RUN go build -i -o /go/bin/codeamp-circuit .

RUN cp /go/bin/codeamp-circuit /usr/local/bin/codeamp-circuit

