apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:    
    - image: gcr.io/codeamp/circuit
      sync:
        manual:
          - src: './'
            dest: /go/src/github.com/codeamp/circuit
  local: 
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
      - ./kubernetes/k8s-*