apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: kube-system
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":""},"labels":{"app":"kube2iam"},"name":"kube2iam","namespace":"kube-system"},"spec":{"template":{"metadata":{"labels":{"name":"kube2iam"}},"spec":{"containers":[{"args":["--app-port=8282","--auto-discover-base-arn","--auto-discover-default-role","--iptables=true","--host-ip=$(HOST_IP)","--host-interface=cali+"],"env":[{"name":"HOST_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}}],"image":"jtblin/kube2iam:0.7.0","name":"kube2iam","ports":[{"containerPort":8282,"hostPort":8282,"name":"http"}],"resources":{"limits":{"cpu":"10m","memory":"32Mi"},"requests":{"cpu":"10m","memory":"32Mi"}},"securityContext":{"privileged":true}}],"hostNetwork":true,"serviceAccountName":"kube2iam","tolerations":[{"effect":"NoSchedule","operator":"Exists"},{"effect":"NoExecute","operator":"Exists"},{"key":"CriticalAddonsOnly","operator":"Exists"}]}},"updateStrategy":{"type":"RollingUpdate"}}}
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  generation: 1
  labels:
    app: kube2iam
  name: kube2iam
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/daemonsets/kube2iam
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: kube2iam
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube2iam
    spec:
      containers:
      - args:
        - --app-port=8282
        - --auto-discover-base-arn
        - --auto-discover-default-role
        - --iptables=true
        - --host-ip=$(HOST_IP)
        - --host-interface=cali+
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: jtblin/kube2iam:0.7.0
        imagePullPolicy: IfNotPresent
        name: kube2iam
        ports:
        - containerPort: 8282
          hostPort: 8282
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 256m
          requests:
            cpu: 50m
            memory: 256m
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube2iam
      serviceAccountName: kube2iam
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
  templateGeneration: 2
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
