#!/bin/bash
set -e

export PGPASSWORD=$POSTGRES_PASSWORD
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER dex;
  CREATE DATABASE dex;
	GRANT ALL PRIVILEGES ON DATABASE dex TO dex;
EOSQL
